# Файл конфигурации LiteLLM v1.70.0
# Раздел 3: Создание главного файла конфигурации config.yaml

general_settings:
  # Мастер-ключ для аутентификации на прокси. Значение берется из переменной окружения.
  master_key: "os.environ/LITELLM_MASTER_KEY"
  # URL для подключения к базе данных PostgreSQL. Значение берется из переменной окружения.
  database_url: "os.environ/DATABASE_URL"
  # Включает хранение моделей в базе данных. Это ключевая настройка для данного развертывания.
  store_model_in_db: True

litellm_settings:
  # Конфигурация кеша Redis
  cache:
    # Тип кеша
    type: "redis"
    # Хост Redis. Значение берется из переменной окружения.
    host: "os.environ/UPSTASH_REDIS_HOST"
    # Порт Redis. Значение берется из переменной окружения.
    port: "os.environ/UPSTASH_REDIS_PORT"
    # Пароль Redis. Значение берется из переменной окружения.
    password: "os.environ/UPSTASH_REDIS_PASSWORD"
  # КРИТИЧЕСКИ ВАЖНО: Полное отключение fallbacks для предотвращения использования VertexAI
  # Это предотвращает автоматическое переключение на другие провайдеры при ошибках
  default_fallbacks: []

router_settings:
  # Стратегия маршрутизации - простое случайное распределение
  # Это обеспечивает равномерное распределение нагрузки между 120 ключами API
  routing_strategy: "simple-shuffle"

# Список моделей оставлен пустым, так как модели будут загружаться из базы данных
# Это позволяет динамически управлять моделями через API или скрипты
model_list: []